export const TEAM_FLAGS = {
  Algeria: "https://flagcdn.com/w20/dz.png",
  Argentina: "https://flagcdn.com/w20/ar.png",
  Australia: "https://flagcdn.com/w20/au.png",
  Austria: "https://flagcdn.com/w20/at.png",
  Belgium: "https://flagcdn.com/w20/be.png",
  "Bosnia & Herzegovina": "https://flagcdn.com/w20/ba.png",
  Brazil: "https://flagcdn.com/w20/br.png",
  Canada: "https://flagcdn.com/w20/ca.png",
  "Cape Verde": "https://flagcdn.com/w20/cv.png",
  Colombia: "https://flagcdn.com/w20/co.png",
  Croatia: "https://flagcdn.com/w20/hr.png",
  "Curaçao": "https://flagcdn.com/w20/cw.png",
  "Czech Republic": "https://flagcdn.com/w20/cz.png",
  "DR Congo": "https://flagcdn.com/w20/cd.png",
  Ecuador: "https://flagcdn.com/w20/ec.png",
  Egypt: "https://flagcdn.com/w20/eg.png",
  England: "https://flagcdn.com/w20/gb-eng.png",
  France: "https://flagcdn.com/w20/fr.png",
  Germany: "https://flagcdn.com/w20/de.png",
  Ghana: "https://flagcdn.com/w20/gh.png",
  Haiti: "https://flagcdn.com/w20/ht.png",
  Iran: "https://flagcdn.com/w20/ir.png",
  Iraq: "https://flagcdn.com/w20/iq.png",
  "Ivory Coast": "https://flagcdn.com/w20/ci.png",
  Japan: "https://flagcdn.com/w20/jp.png",
  Jordan: "https://flagcdn.com/w20/jo.png",
  Mexico: "https://flagcdn.com/w20/mx.png",
  Morocco: "https://flagcdn.com/w20/ma.png",
  Netherlands: "https://flagcdn.com/w20/nl.png",
  "New Zealand": "https://flagcdn.com/w20/nz.png",
  Norway: "https://flagcdn.com/w20/no.png",
  Panama: "https://flagcdn.com/w20/pa.png",
  Paraguay: "https://flagcdn.com/w20/py.png",
  Portugal: "https://flagcdn.com/w20/pt.png",
  Qatar: "https://flagcdn.com/w20/qa.png",
  "Saudi Arabia": "https://flagcdn.com/w20/sa.png",
  Scotland: "https://flagcdn.com/w20/gb-sct.png",
  Senegal: "https://flagcdn.com/w20/sn.png",
  "South Africa": "https://flagcdn.com/w20/za.png",
  "South Korea": "https://flagcdn.com/w20/kr.png",
  Spain: "https://flagcdn.com/w20/es.png",
  Sweden: "https://flagcdn.com/w20/se.png",
  Switzerland: "https://flagcdn.com/w20/ch.png",
  Tunisia: "https://flagcdn.com/w20/tn.png",
  Turkey: "https://flagcdn.com/w20/tr.png",
  USA: "https://flagcdn.com/w20/us.png",
  Uruguay: "https://flagcdn.com/w20/uy.png",
  Uzbekistan: "https://flagcdn.com/w20/uz.png",
};